query GetActivity($id: ID!, $lang: String!) {
  activity: activities_by_id(id: $id) {
    id
    translations(filter: {languages_code: {_eq: $lang} }) {
      title
      content
    }
    steps {
      id
      translations(filter: {languages_code: {_eq: $lang} }) {
        title
        content
      }
      toolfamilies {
        categories_id {
          id
          translations(filter: {languages_code: {_eq: $lang} }) {
            title
          }
        }
      }
      annexes(sort: ["sort"]) {
        id
        translations(filter: {languages_code: {_eq: $lang} }) {
          title
          content
        }
      }
      resources(sort: ["resources_id.title"], filter: { resources_id: { languages: { languages_code: { _eq: $lang } } } } ) {
        resources_id {
          id
          title
          date
          author
          type
          tutorial
          url
        }
      }
    }
  }
}

query GetActivities($lang: String!) {
  activities: activities {
    id
    translations(filter: {languages_code: {_eq: $lang} }) {
      title
    }
  }
}